{"name": "test_add_user_incorrect_username_length", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 400", "trace": "self = <tests.test_api.TestApi object at 0x115887b90>\napi_client = <api.api_client.ApiClient object at 0x116203dd0>\n\n    def test_add_user_incorrect_username_length(self, api_client):\n        \"\"\"\n        Тестируется негативный сценарий, когда производится попытка добавить пользователя с некорректной\n        длиной поля \"username\"\n        Ожидаемый статус код - 400 \"Плохой запрос\"\n        АPI работает некорректно: пользователь с таким username добавляется в базу и возвращается статус-код 210\n        \"\"\"\n        username = 'q'\n        result = api_client.reg_user(username, 'qqqqqqqq@yandex.ru', 'rwrwerwerwr')\n        self.builder.del_user(username)\n>       assert result == 400\nE       assert 210 == 400\n\ntests/test_api.py:42: AssertionError"}, "description": "\n        Тестируется негативный сценарий, когда производится попытка добавить пользователя с некорректной\n        длиной поля \"username\"\n        Ожидаемый статус код - 400 \"Плохой запрос\"\n        АPI работает некорректно: пользователь с таким username добавляется в базу и возвращается статус-код 210\n        ", "start": 1590610457797, "stop": 1590610457908, "uuid": "1bb460b6-f0f6-410f-b8ac-2496a5b026d3", "historyId": "2cbbce40a42f5d275076d85e9d05761a", "testCaseId": "25abbac26a984d5bc15d75cb2b95af50", "fullName": "tests.test_api.TestApi#test_add_user_incorrect_username_length", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "MacBook-Air-Roman-2.local"}, {"name": "thread", "value": "20864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}